# Generated by Django 6.0.5 on 2026-05-06 13:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Nazwa usługi')),
                ('description', models.TextField(blank=True, verbose_name='Opis usługi')),
                ('price', models.DecimalField(decimal_places=2, max_digits=7, verbose_name='Cena (zł)')),
                ('duration_minutes', models.IntegerField(verbose_name='Czas trwania (minuty)')),
            ],
        ),
        migrations.CreateModel(
            name='Staff',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50, verbose_name='Imię')),
                ('last_name', models.CharField(max_length=50, verbose_name='Nazwisko')),
                ('specialization', models.CharField(max_length=100, verbose_name='Specjalizacja')),
            ],
        ),
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='Data wizyty')),
                ('time', models.TimeField(verbose_name='Godzina wizyty')),
                ('is_confirmed', models.BooleanField(default=False, verbose_name='Czy potwierdzona?')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Klient')),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bookings.service', verbose_name='Usługa')),
                ('staff', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bookings.staff', verbose_name='Pracownik')),
            ],
            options={
                'unique_together': {('staff', 'date', 'time')},
            },
        ),
    ]
