# Generated by Django 6.0.5 on 2026-05-06 20:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0002_service_icon_class_alter_service_description_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='appointment',
            options={'verbose_name': 'Wizyta', 'verbose_name_plural': 'Wizyty'},
        ),
        migrations.AlterModelOptions(
            name='service',
            options={'verbose_name': 'Usługa', 'verbose_name_plural': 'Usługi'},
        ),
        migrations.AlterModelOptions(
            name='staff',
            options={'verbose_name': 'Pracownik', 'verbose_name_plural': 'Pracownicy'},
        ),
        migrations.RemoveField(
            model_name='appointment',
            name='is_confirmed',
        ),
        migrations.AddField(
            model_name='appointment',
            name='internal_notes',
            field=models.TextField(blank=True, null=True, verbose_name='Notatki personelu (widoczne tylko w panelu)'),
        ),
        migrations.AddField(
            model_name='appointment',
            name='source',
            field=models.CharField(choices=[('ONLINE', 'Strona WWW (Online)'), ('PHONE', 'Telefonicznie'), ('WALKIN', 'Osobiście (W salonie)')], default='ONLINE', max_length=10, verbose_name='Źródło rezerwacji'),
        ),
        migrations.AddField(
            model_name='appointment',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Oczekująca (Nowa)'), ('CONFIRMED', 'Potwierdzona'), ('COMPLETED', 'Zrealizowana'), ('CANCELED', 'Odwołana'), ('NOSHOW', 'Nieobecność (No-show)')], default='PENDING', max_length=10, verbose_name='Status wizyty'),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Data utworzenia zapisu'),
        ),
        migrations.AlterField(
            model_name='service',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='Opis'),
        ),
        migrations.AlterField(
            model_name='service',
            name='duration_minutes',
            field=models.IntegerField(verbose_name='Czas trwania (min)'),
        ),
        migrations.AlterField(
            model_name='service',
            name='icon_class',
            field=models.CharField(default='fa-sparkles', max_length=50, verbose_name='Ikona (FontAwesome)'),
        ),
        migrations.AlterField(
            model_name='service',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Nazwa usługi'),
        ),
        migrations.AlterField(
            model_name='service',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Cena'),
        ),
    ]
