# Generated by Django 6.0.5 on 2026-05-07 08:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0003_alter_appointment_options_alter_service_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Attendance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='Data')),
                ('is_present', models.BooleanField(default=False, verbose_name='Obecny w pracy')),
                ('staff', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendances', to='bookings.staff', verbose_name='Pracownik')),
            ],
            options={
                'verbose_name': 'Obecność',
                'verbose_name_plural': 'Obecności',
                'unique_together': {('staff', 'date')},
            },
        ),
    ]
