# Generated by Django 6.0.5 on 2026-05-07 11:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0004_attendance'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='payment_method',
            field=models.CharField(blank=True, choices=[('CASH', 'Gotówka'), ('CARD', 'Karta'), ('BLIK', 'BLIK'), ('VOUCHER', 'Voucher'), ('OTHER', 'Inna')], max_length=10, null=True),
        ),
    ]
